Set more modules as upgrade-only
silverstripe/cwp-recipe-kitchen-sink pull request #77
Opened 2020-11-19 21:22 UTC by emteknetnz

2020-11-19 21:29 UTC, Cheddam commented on .cow.json
> +    "undefinedoffset/sortablegridfield"
A lot of these modules aren't actually included in the list of modules Cow attempts to release anyway, so we can shorten this significantly.

```suggestion
    "silverstripe/subsites",
    "tractorcow/silverstripe-fluent",
```

2020-11-20 00:21 UTC, emteknetnz commented
Travis failure is, strange?

![image](https://user-images.githubusercontent.com/4809037/99740132-36581200-2b33-11eb-8eea-7e07e333c751.png)

@Cheddam any idea?  Related to composer 2 possibly (though haven't seen this happen on any other modules)?

2020-11-20 01:22 UTC, Cheddam commented
Looks like this failure emerged [2 weeks ago](https://travis-ci.com/github/silverstripe/cwp-recipe-kitchen-sink/jobs/429505827), and the most obvious difference between it and [the previous build](https://travis-ci.com/github/silverstripe/cwp-recipe-kitchen-sink/jobs/427892413) is Composer 2, so I'd put money on that being the cause.

2020-11-23 04:57 UTC, Cheddam requested changes
The subsites addition is working, but the `tractorcow/silverstripe-fluent` entry needs to go in [cwp/cwp-installer](https://github.com/silverstripe/cwp-installer/blob/2.7/.cow.json), as Cow only looks at one level of config for upgrade-only entries.

2020-11-23 21:18 UTC, Cheddam approved these changes
Looking good, will MOG (need to tidy up the commit message.)

2020-11-23 21:31 UTC, Cheddam commented
The remaining failure is unrelated, merging.

2020-11-23 21:32 UTC, merged